namespace ElectrumGames.GlobalEnums
{
    public enum ItemType
    {
        FlashLightSmall = 0,
        FlashLightMedium,
        FlashLightBig,
        FlashLightUV = 10,
        GlowStickUV,
        GlowStickRed,
        FlashLightUVBig,
        ThermometerAnalog = 20,
        ThermometerElectronic,
        ThermometerAdvanced,
        EMFSimple = 30,
        EMFElectronic,
        EMFAdvanced,
        RadioSimple = 40,
        RadioElectronic,
        RadioAdvanced,
        RadiometerSimple = 50,
        RadiometerElectronic,
        RadiometerAdvanced,
        Matches = 60,
        LighterSimple,
        LighterAdvanced,
        CandleSmall = 70,
        CandleMedium,
        CandleBig,
        SanityRestorerSmall = 80,
        SanityRestorerMedium,
        SanityRestorerAdvanced,
        SaltPackageSmall = 90,
        SaltPackageMedium,
        SaltPackageBig,
        NotebookSimple = 100,
        NotebookMedium,
        NotebookAdvanced,
        CrucifixSmall = 110,
        CrucifixMedium,
        CrucifixBig,
        IncenseSimple = 120,
        IncenseNormal,
        IncenseAdvanced,
        
        PlateRoundWhite = 1000,
        PlateRoundBrown,
        
        KnifeForBread = 1010,
        KnifeChopper,
        KnifeLarge,
        KnifeSmall,
        
        ForkBig = 1020,
        BigSpoon,
        
        Pan = 1030,
        PanWok,
        
        CupPlastic = 1040,
        CupPlasticRed,
        CupSmall,
        GlassDrink,
        GlassIrishCoffee,
        MokkaPot,
        PotCoffee,
        Teapot,
        
        RumBottle = 1050,
        PlasticBottle,
        WaterCoolerBottle,
        WhineBottleRed,
        WhineBottleWhite,
        
        Wrench0 = 1060,
        Wrench1,
        
        WireCutters = 1070
    }
}